export const data = [
  {
    id: 353,
    order_no: "SUBA_20231222",
    order_type: "design_change",
    order_date: "2023-12-22",
    details: "",
    customer_name: "SUBARU",
    event_name: "ABC",
    customer_contact_no: "096-626-5057",
    part_count: 1,
    no_of_parts: 1,
    approved_part_count: 1,
    order_status: "draft",
    order_parts: [
      {
        id: 70,
        order_id: 147,
        part_source: "Outsource",
        part_number: "ZX_D16T_001",
        part_name: "PART 1",
        material_quantity: 12,
        material_arrival_date: "2023-10-31T05:20:19.430Z",
        completion_sign: "Delivery Completed",
        part_relation: "AAYYY",
      },
      {
        id: 71,
        order_id: 147,
        part_source: "Rapiit",
        part_number: "ZX_D16T_002",
        part_name: "PART 2",
        material_quantity: 15,
        material_arrival_date: "2023-10-31T05:20:49.690Z",
        completion_sign: "Partially Completed ",
        part_relation: "Parent",
      },
    ],
    status: {
      approved: 1,
      completed: 0,
      draft: 0,
      in_production: 0,
      unapproved: 0,
    },
  },
  {
    id: 352,
    order_no: "SG_20231218",
    order_type: "design_change",
    order_date: "2023-12-18",
    details: "",
    customer_name: "SGK",
    event_name: "澤田様",
    customer_contact_no: "056-457-7003",
    part_count: 1,
    no_of_parts: 1,
    approved_part_count: 1,
    order_status: "draft",
    order_parts: [
      {
        id: 70,
        order_id: 147,
        part_source: "Outsource",
        part_number: "ZX_D16T_001",
        part_name: "PART 1",
        material_quantity: 12,
        material_arrival_date: "2023-10-31T05:20:19.430Z",
        completion_sign: "Delivery Completed",
        part_relation: "AAYYY",
        delivery_installments: [
          {
            delivery_date: "2023-10-31",
            delivery_quantity: 12,
            completion_sign: "Delivery Completed",
          },
          {
            delivery_date: "2023-11-01",
            delivery_quantity: 5,
            completion_sign: "Delivery Completed",
          },
        ],
      },
      {
        id: 71,
        order_id: 147,
        part_source: "Rapiit",
        part_number: "ZX_D16T_002",
        part_name: "PART 2",
        material_quantity: 15,
        material_arrival_date: "2023-10-31T05:20:49.690Z",
        completion_sign: "Partially Completed ",
        part_relation: "Parent",
      },
      {
        id: 72,
        order_id: 147,
        part_source: "Outsource",
        part_number: "ZX_D16T_003",
        part_name: "PART 3",
        material_quantity: 12,
        material_arrival_date: "2023-10-31T05:21:41.636Z",
        completion_sign: "Partially Completed ",
        part_relation: "AAYYY",
      },
    ],
    status: {
      approved: 1,
      completed: 0,
      draft: 0,
      in_production: 0,
      unapproved: 0,
    },
  },
  {
    id: 351,
    order_no: "CRT_20231213",
    order_type: "design_change",
    order_date: "2023-12-13",
    details: "",
    customer_name: "クレファクト",
    event_name: "小郷様",
    customer_contact_no: "086-693-1131",
    part_count: 2,
    no_of_parts: 2,
    approved_part_count: 2,
    order_status: "draft",
    status: {
      approved: 1,
      completed: 0,
      draft: 0,
      in_production: 1,
      unapproved: 0,
    },
  },
  {
    id: 350,
    order_no: "SUBA_20231211",
    order_type: "design_change",
    order_date: "2023-12-11",
    details: "",
    customer_name: "SUBARU",
    event_name: "FYGH",
    customer_contact_no: "096-626-5057",
    part_count: 1,
    no_of_parts: 1,
    approved_part_count: 0,
    order_status: "draft",
    status: {
      approved: 0,
      completed: 0,
      draft: 1,
      in_production: 0,
      unapproved: 0,
    },
  },
  {
    id: 349,
    order_no: "CRT_20231129",
    order_type: "design_change",
    order_date: "2023-11-29",
    details: "",
    customer_name: "クレファクト",
    event_name: "小郷様",
    customer_contact_no: "086-693-1131",
    part_count: 0,
    no_of_parts: 0,
    approved_part_count: 0,
    order_status: "draft",
    status: {
      approved: 0,
      completed: 0,
      draft: 0,
      in_production: 0,
      unapproved: 0,
    },
  },
  {
    id: 348,
    order_no: "CCM N_20231129",
    order_type: "design_change",
    order_date: "2023-11-29",
    details: "",
    customer_name: "シーコム名古屋",
    event_name: "山下様",
    customer_contact_no: "056-575-3888",
    part_count: 0,
    no_of_parts: 0,
    approved_part_count: 0,
    order_status: "draft",
    status: {
      approved: 0,
      completed: 0,
      draft: 0,
      in_production: 0,
      unapproved: 0,
    },
  },
  {
    id: 347,
    order_no: "SUBA_20231120",
    order_type: "design_change",
    order_date: "2023-11-20",
    details: "",
    customer_name: "SUBARU",
    event_name: "JKHGF",
    customer_contact_no: "096-626-5057",
    part_count: 2,
    no_of_parts: 2,
    approved_part_count: 2,
    order_status: "draft",
    status: {
      approved: 2,
      completed: 0,
      draft: 0,
      in_production: 0,
      unapproved: 0,
    },
  },
  {
    id: 346,
    order_no: "SG_20231120",
    order_type: "design_change",
    order_date: "2023-11-20",
    details: "",
    customer_name: "SGK",
    event_name: "澤田様",
    customer_contact_no: "056-457-7003",
    part_count: 2,
    no_of_parts: 2,
    approved_part_count: 2,
    order_status: "draft",
    status: {
      approved: 2,
      completed: 0,
      draft: 0,
      in_production: 0,
      unapproved: 0,
    },
  },
  {
    id: 345,
    order_no: "SG_20231115",
    order_type: "design_change",
    order_date: "2023-11-15",
    details: "",
    customer_name: "SGK",
    event_name: "澤田様",
    customer_contact_no: "056-457-7003",
    part_count: 1,
    no_of_parts: 1,
    approved_part_count: 1,
    order_status: "draft",
    status: {
      approved: 0,
      completed: 0,
      draft: 0,
      in_production: 1,
      unapproved: 0,
    },
  },
  {
    id: 344,
    order_no: "CRT_20231113",
    order_type: "design_change",
    order_date: "2023-11-13",
    details: "",
    customer_name: "クレファクト",
    event_name: "小郷様",
    customer_contact_no: "086-693-1131",
    part_count: 4,
    no_of_parts: 4,
    approved_part_count: 4,
    order_status: "draft",
    status: {
      approved: 2,
      completed: 0,
      draft: 0,
      in_production: 2,
      unapproved: 0,
    },
  },
];

export const partsData = [
  {
    id: 70,
    order_id: 147,
    part_source: "Outsource",
    part_no: "ZX_D16T_001",
    name: "PART 1",
    quantity: 12,
    delivery_date: "2023-10-31T05:20:19.430Z",
    content_of_production: "AAA",
    status: "approved",
    parent_part: {
      id: null,
      name: null,
      part_no: null,
    },
    part_orientation: {
      id: 7,
      name: "PartOrie",
    },
    part_relation: {
      id: 9,
      name: "AAYYY",
      parent_part_reference: false,
    },
    part_type: {
      id: 12,
      name: "Manufacturing",
    },
    difficulty_level: "S- Difficulty",
  },
  {
    id: 71,
    order_id: 147,
    part_source: "Rapiit",
    part_no: "ZX_D16T_002",
    name: "PART 2",
    quantity: 15,
    delivery_date: "2023-10-31T05:20:49.690Z",
    content_of_production: "WW",
    status: "approved",
    parent_part: {
      id: null,
      name: null,
      part_no: null,
    },
    part_orientation: {
      id: 6,
      name: "DDD",
    },
    part_relation: {
      id: 10,
      name: "Parent",
      parent_part_reference: false,
    },
    part_type: {
      id: 13,
      name: "Assembly",
    },
    difficulty_level: "A High",
  },
  {
    id: 72,
    order_id: 147,
    part_source: "Outsource",
    part_no: "ZX_D16T_003",
    name: "PART 3",
    quantity: 12,
    delivery_date: "2023-10-31T05:21:41.636Z",
    content_of_production: "LL",
    status: "approved",
    parent_part: {
      id: null,
      name: null,
      part_no: null,
    },
    part_orientation: {
      id: 5,
      name: "CCC",
    },
    part_relation: {
      id: 9,
      name: "AAYYY",
      parent_part_reference: false,
    },
    part_type: {
      id: 7,
      name: "Nidhi",
    },
    difficulty_level: "C Low",
  },
  {
    id: 73,
    order_id: 147,
    part_source: "Outsource",
    part_no: "ZX_D16T_004",
    name: "PART 4",
    quantity: 15,
    delivery_date: "2023-11-20T09:35:51.699Z",
    content_of_production: "DDD",
    status: "approved",
    parent_part: {
      id: null,
      name: null,
      part_no: null,
    },
    part_orientation: {
      id: 7,
      name: "PartOrie",
    },
    part_relation: {
      id: 16,
      name: "Common",
      parent_part_reference: false,
    },
    part_type: {
      id: 9,
      name: "artType",
    },
    difficulty_level: "A High",
  },
  {
    id: 75,
    order_id: 147,
    part_source: "Outsource",
    part_no: "ZX_D16T_005",
    name: "PART 5",
    quantity: 12,
    delivery_date: "2023-11-28T05:45:35.902Z",
    content_of_production: "Testing",
    status: "approved",
    parent_part: {
      id: null,
      name: null,
      part_no: null,
    },
    part_orientation: {
      id: 7,
      name: "PartOrie",
    },
    part_relation: {
      id: 11,
      name: "Testinghhh",
      parent_part_reference: false,
    },
    part_type: {
      id: 12,
      name: "Manufacturing",
    },
    difficulty_level: "S- Difficulty",
  },
  {
    id: 76,
    order_id: 147,
    part_source: "Outsource",
    part_no: "ZX_D16T_006",
    name: "PART 6",
    quantity: 15,
    delivery_date: "2023-11-28T06:01:23.432Z",
    content_of_production: "PPP",
    status: "approved",
    parent_part: {
      id: null,
      name: null,
      part_no: null,
    },
    part_orientation: {
      id: 5,
      name: "CCC",
    },
    part_relation: {
      id: 14,
      name: "rrr",
      parent_part_reference: false,
    },
    part_type: {
      id: 13,
      name: "Assembly",
    },
    difficulty_level: "S Difficulty",
  },
  {
    id: 77,
    order_id: 147,
    part_source: "Rapiit",
    part_no: "ZX_D16T_007",
    name: "PART 7",
    quantity: 12,
    delivery_date: "2023-11-28T06:02:26.353Z",
    content_of_production: "III",
    status: "approved",
    parent_part: {
      id: null,
      name: null,
      part_no: null,
    },
    part_orientation: {
      id: 6,
      name: "DDD",
    },
    part_relation: {
      id: 9,
      name: "AAYYY",
      parent_part_reference: false,
    },
    part_type: {
      id: 9,
      name: "artType",
    },
    difficulty_level: "S- Difficulty",
  },
];
